version: 2
jobs:
  lint_build_test:
    environment:
      BASH_ENV: /etc/profile
    docker:
      - image: harshjv/liquality-cal-dev
    working_directory: ~/chainabstractionlayer
    steps:
      - checkout
      - run:
          name: bitcoind
          command: bitcoind-daemon
      - run:
          name: parity
          command: parity-daemon
      - run:
          name: node 8
          command: . /root/.nvm/nvm.sh && nvm install 8
      - run:
          name: npm install
          command: . /root/.nvm/nvm.sh && nvm use 8 && npm install
      - run:
          name: lint
          command: . /root/.nvm/nvm.sh && nvm use 8 && npm run lint
      - run:
          name: build
          command: . /root/.nvm/nvm.sh && nvm use 8 && npm run build
      - run:
          name: test
          command: . /root/.nvm/nvm.sh && nvm use 8 && npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint_build_test
